spring:
  application:
    name: order-execution-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bitbuddy}
    username: ${DATASOURCE_USERNAME:bitbuddy}
    password: ${DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: order_execution
  flyway:
    enabled: true
    schemas: order_execution
    default-schema: order_execution
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: latest
      group-id: order-execution-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ch.ost.clde.dto"   # dein common DTO-Package

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

trading:
  exchange-hot: ${TRADING_EXCHANGE_HOT:false}

cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000,https://yourdomain.com"