apiVersion: v1
kind: Service
metadata:
  name: bitbuddy-frontend
  namespace: bitbuddy
spec:
  type: LoadBalancer
  selector:
    app: bitbuddy-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
